// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ScanDirectory(arg1:string,arg2:boolean,arg3:boolean):Promise<backend.ScanResult>;

export function SearchFiles(arg1:string,arg2:number):Promise<Array<backend.FileDTO>>;

export function SemanticSearch(arg1:string,arg2:number):Promise<Array<backend.FileDTO>>;

export function SuggestOrganization(arg1:string,arg2:number,arg3:number):Promise<backend.OrganizeReportDTO>;
