// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ScanDirectory(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ScanDirectory'](arg1, arg2, arg3);
}

export function SearchFiles(arg1, arg2) {
  return window['go']['backend']['App']['SearchFiles'](arg1, arg2);
}

export function SemanticSearch(arg1, arg2) {
  return window['go']['backend']['App']['SemanticSearch'](arg1, arg2);
}

export function SuggestOrganization(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SuggestOrganization'](arg1, arg2, arg3);
}
